name: Publish Docker images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        image:
          - cross-riscv64gc-unknown-linux-musl
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          tags: |
            {{sha}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/${{ matrix.image }}.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
